### Example config:
#sections:
#  -
#    refTop: [0, 0, 0]
#    refBottom: [83, 1, -83]
#    region: [128, 128, -128, -128]
#    world: TestWorld
#  -
#    refTop: [371, 242, -83]
#    refBottom: [0, 0, 0]
#    region: [196, -92, 380, 92]
#    world: TestWorld
#    name: section1

# The damage players will take when outside a managed section
# damage-outside-sections: 0.0